config/routes.rb
Rails.application.routes.draw do

  # Dynamic redirects
  get "/built" => redirect("http://work.stevegrossi.com")
  get "/built/:slug" => redirect("http://work.stevegrossi.com")
  get "/wrote/:slug" => redirect("/on/%{slug}")
  get "/thoughts/about/:slug" => redirect("/on/topics/%{slug}")
  get "/thoughts/:slug" => redirect("/on/%{slug}")
  get "/read/:slug" => redirect("/on/%{slug}")
  get "/read/authors/:slug" => redirect("/on/books/by/%{slug}")

  root to: redirect("/on")

  get "/404" => 'errors#error_404'
  get "/422" => 'errors#error_422'
  get "/500" => 'errors#error_500'

  scope :meta do
    devise_for :users, skip: [:sessions, :registrations]
    as :user do
      get "in" => 'devise/sessions#new', as: :new_user_session
      post "in" => 'devise/sessions#create', as: :user_session
      get "out" => 'devise/sessions#destroy', as: :destroy_user_session
    end
  end

  namespace :meta do
    resources :books do
      post "finish" => 'books#finish'
    end
    resources :authors, :redirects, :posts
    resources :pages, constraints: { id: /.*/ }
    root to: 'dashboard#home', as: :dashboard
  end

  resources :posts, path: "on", only: [:index, :show] do
    collection do
      get "page/:page", action: :index, as: :paged
      get "topics" => 'posts#tags', as: :tags
      get "topics/:slug" => 'posts#tag', as: :tagged
      resources :books, only: [:index, :show] do
        collection do
          resources :authors, only: [:index, :show], path: "by"
        end
      end
    end
  end

  get "search" => 'static_pages#search'
  get "feed" => 'static_pages#feed', defaults: { format: :rss }

  get ":id", to: 'pages#show', as: :page, constraints: { id: /.*/ }

end

app/models/author.rb
class Author < ActiveRecord::Base

  extend FriendlyId
  friendly_id :full_name

  has_many :authorships, dependent: :destroy
  has_many :books, through: :authorships

  default_scope { order("lower(lname), fname, mname") }

  validates :fname, presence: true,
                    uniqueness: { scope: [:lname, :mname] }
  validates :lname, presence: true

  def full_name
    [fname, mname, lname].compact.join(" ")
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.includes(:books)
  end

  def show
    @author = Author.includes(books: [:post, :authors]).find(params[:id])
    @books = @author.books.order("pub_year DESC") if @author
  end

end

app/controllers/meta/authors_controller.rb
class Meta::AuthorsController < Meta::DashboardController

  def index
    @authors = Author.includes(:books)
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: view_context.notify(:new, :author) }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      redirect_to @author, notice: view_context.notify(:updated, :author)
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    name = @author.full_name
    @author.destroy
    redirect_to meta_authors_path, notice: "You deleted <b>#{name}</b>"
  end

  private

  def author_params
    params.require(:author).permit(:fname, :mname, :lname)
  end

end

app/views/authors/_author.html.slim
li
  => link_to(author.full_name, author)
  = "(#{author.books.size})"

app/views/authors/_form.html.erb
<%= flash_errors(@author) %>

<%= form_for(@author) do |f| %>

    <%= f.label :fname, 'First' %>
    <%= f.text_field :fname, tabindex: 1 %>

    <%= f.label :mname, 'Middle' %>
    <%= f.text_field :mname, tabindex: 2 %>

    <%= f.label :lname, 'Last' %>
    <%= f.text_field :lname, tabindex: 3 %>

    <p><%= f.submit %>
      <%= link_to 'or go back', @author, class: :cancel if params[:controller] == :authors %>
    </p>

<% end %>

app/views/authors/create.js.erb
<% if @author.save %>
  $(document).trigger('close.facebox');
  $('#book_author_ids').prepend('<option value="<%= @author.id %>" selected="selected"><%= escape_javascript @author.full_name %></option>');
<% else %>
  $('#facebox .content').html('<%= escape_javascript(render template: "authors/new.html") %>');
  $('#facebox form').data('remote','true');
<% end %>

app/views/authors/index.html.slim
- provide :title, 'All Authors I’ve Read'

h1.Title I’ve Been Reading

- if @authors.present?
  ol.ColumnList
    = render @authors
- else
  p Hm, actually it looks like I haven’t read any books yet. To the library!

app/views/authors/show.html.slim
h1.Title
  span.Title-eyebrow Books I’ve Read By
  = @author.full_name

- if @books.present?
  ol.ArticleList
    = render @books
- else
  p Hm, it looks like I actually haven’t read any of #{ @author.fname }’s books. To the library!
p
  = link_to('« All authors', authors_path)